swagger: "2.0"
info:
  description: Blood Donor API
  version: 0.0.1
  title: Yesod REST API
  contact:
    name: Barry Moore
    email: chiroptical@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: localhost:3000
basePath: "/api"
tags:
- name: donor-api
  description: Donor API
paths:
  "/donors":
    get:
      tags:
      - donor-api
      summary: View all donors
      operationId: getDonors
      produces:
      - "*/*"
      responses:
        "200":
          description: Successfully retrieved all donors
          schema:
            $ref: "#/definitions/Donors"
        "401":
          description: You are not authorized to view the resource
        "403":
          description: Accessing the resource you were trying to reach is forbidden
        "404":
          description: The resource you were trying to reach is not found
        "500":
          description: Application failed to process the request
      deprecated: false
    post:
      tags:
      - donor-api
      summary: Create a new donor
      operationId: postDonor
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - in: body
        name: donor
        description: donor
        required: true
        schema:
          $ref: "#/definitions/Donor"
      responses:
        "200":
          description: Successfully created a new donor
        "201":
          description: Created
        "401":
          description: You are not authorized to view the resource
        "403":
          description: Accessing the resource you were trying to reach is forbidden
        "404":
          description: The resource you were trying to reach is not found
        "500":
          description: Application failed to process the request
      deprecated: false
    put:
      tags:
      - donor-api
      summary: Update a donor"s information
      operationId: putDonor
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - in: body
        name: donor
        description: donor
        required: true
        schema:
          $ref: "#/definitions/Donor"
      responses:
        "200":
          description: Successfully updated donor information
        "201":
          description: Created
        "401":
          description: You are not authorized to view the resource
        "403":
          description: Accessing the resource you were trying to reach is forbidden
        "404":
          description: The resource you were trying to reach is not found
        "500":
          description: Application failed to process the request
      deprecated: false
  "/donors/{id}":
    get:
      tags:
      - donor-api
      summary: Retrieve specific donor with the supplied donor id
      operationId: getDonorWithId
      produces:
      - "*/*"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: Successfully retrieved the donor with the supplied id
        "401":
          description: You are not authorized to view the resource
        "403":
          description: Accessing the resource you were trying to reach is forbidden
        "404":
          description: The resource you were trying to reach is not found
        "500":
          description: Application failed to process the request
      deprecated: false
    delete:
      tags:
      - donor-api
      summary: Deletes specific donor with the supplied donor id
      operationId: deleteDonorWithId
      produces:
      - "*/*"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: Successfully deletes the specific donor
        "204":
          description: No Content
        "401":
          description: You are not authorized to view the resource
        "403":
          description: Accessing the resource you were trying to reach is forbidden
        "404":
          description: The resource you were trying to reach is not found
        "500":
          description: Application failed to process the request
      deprecated: false
definitions:
  Donor:
    type: object
    properties:
      bloodGroup:
        type: string
      contactNo:
        type: string
      dateOfBirth:
        type: string
        format: date
      donorId:
        type: integer
        format: int64
      emergencyContactNo:
        type: string
      firstName:
        type: string
      firstTimeDonor:
        type: boolean
      lastName:
        type: string
    title: Donor
  Donors:
    type: array
    items:
      $ref: "#/definitions/Donor"
